--- #YAML:1.0
name: CGI-Session-ExpireSessions
version: 1.05
author:
  - Ron Savage <ron@savage.net.au>
abstract: |-
  Delete expired CGI::Session db-based and file-based sessions
license: artistic
requires:
  Carp: 0
  File::Spec: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  CGI::Session::ExpireSessions:
    file: lib/CGI/Session/ExpireSessions.pm
    version: 1.05
generated_by: Module::Build version 0.2611
