---
name: CGI-Session-ExpireSessions
version: 1.08
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: Delete expired C<CGI::Session>-type db-based and file-based sessions
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  CGI::Session: 4.14
  Carp: 0
  File::Spec: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  CGI::Session::ExpireSessions:
    file: lib/CGI/Session/ExpireSessions.pm
    version: 1.08
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
